# fly.toml app configuration file generated for bens-atlas on 2023-07-06T18:14:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bens-atlas"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
