import { useState } from 'react';

type CountriesObject = {
  [key: string]: boolean | null;
};

const useCountries = () => {
  const [countries, setCountries] = useState({
    Afghanistan: null,
    Albania: null,
    Algeria: null,
    Andorra: null,
    Angola: null,
    'Antigua And Barbuda': null,
    Argentina: null,
    Armenia: null,
    Australia: null,
    Austria: null,
    Azerbaijan: null,
    'Bahamas, The': null,
    Bahrain: null,
    Bangladesh: null,
    Barbados: null,
    Belarus: null,
    Belgium: null,
    Belize: null,
    'Benin (Dahomey)': null,
    Bolivia: null,
    'Bosnia And Herzegovina': null,
    Botswana: null,
    Brazil: null,
    Brunei: null,
    'Brunswick And Lüneburg': null,
    Bulgaria: null,
    'Burkina Faso (Upper Volta)': null,
    Burundi: null,
    'Cabo Verde': null,
    Cambodia: null,
    Cameroon: null,
    Canada: null,
    'Cayman Islands, The': null,
    'Central African Republic': null,
    Chad: null,
    Chile: null,
    China: null,
    Colombia: null,
    Comoros: null,
    'Costa Rica': null,
    'Cote D’ivoire (Ivory Coast)': null,
    Croatia: null,
    Cuba: null,
    Cyprus: null,
    Czechia: null,
    Czechoslovakia: null,
    'Democratic Republic Of The Congo': null,
    Denmark: null,
    Djibouti: null,
    Dominica: null,
    'Dominican Republic': null,
    Ecuador: null,
    Egypt: null,
    'El Salvador': null,
    'Equatorial Guinea': null,
    Eritrea: null,
    Estonia: null,
    Eswatini: null,
    Ethiopia: null,
    Fiji: null,
    Finland: null,
    France: null,
    Gabon: null,
    'Gambia, The': null,
    Georgia: null,
    Germany: null,
    Ghana: null,
    Greece: null,
    Grenada: null,
    Guatemala: null,
    Guinea: null,
    'Guinea-Bissau': null,
    Guyana: null,
    Haiti: null,
    'Hanseatic Republics': null,
    Honduras: null,
    Hungary: null,
    Iceland: null,
    India: null,
    Indonesia: null,
    Iran: null,
    Iraq: null,
    Ireland: null,
    Israel: null,
    Italy: null,
    Jamaica: null,
    Japan: null,
    Jordan: null,
    Kazakhstan: null,
    Kenya: null,
    Korea: null,
    Kosovo: null,
    Kuwait: null,
    Kyrgyzstan: null,
    Laos: null,
    Latvia: null,
    Lebanon: null,
    Lesotho: null,
    Liberia: null,
    Libya: null,
    Liechtenstein: null,
    Lithuania: null,
    Luxembourg: null,
    Madagascar: null,
    Malawi: null,
    Malaysia: null,
    Maldives: null,
    Mali: null,
    Malta: null,
    Mauritania: null,
    Mauritius: null,
    Mexico: null,
    Moldova: null,
    Monaco: null,
    Mongolia: null,
    Montenegro: null,
    Morocco: null,
    Mozambique: null,
    Myanmar: null,
    Namibia: null,
    Nepal: null,
    'Netherlands, The': null,
    'New Zealand': null,
    Nicaragua: null,
    Niger: null,
    Nigeria: null,
    'North Macedonia': null,
    Norway: null,
    Oman: null,
    Pakistan: null,
    Panama: null,
    'Papua New Guinea': null,
    Paraguay: null,
    Peru: null,
    Philippines: null,
    Poland: null,
    Portugal: null,
    Qatar: null,
    'Republic Of Korea (South Korea)': null,
    'Republic Of The Congo': null,
    Romania: null,
    Russia: null,
    Rwanda: null,
    'Saint Lucia': null,
    'Saint Vincent And The Grenadines': null,
    Samoa: null,
    'Saudi Arabia': null,
    Senegal: null,
    Serbia: null,
    'Sierra Leone': null,
    Singapore: null,
    Slovakia: null,
    Slovenia: null,
    'Solomon Islands, The': null,
    Somalia: null,
    'South Africa': null,
    'South Sudan': null,
    Spain: null,
    'Sri Lanka': null,
    Sudan: null,
    Suriname: null,
    Sweden: null,
    Switzerland: null,
    Syria: null,
    Tajikistan: null,
    Tanzania: null,
    Thailand: null,
    Togo: null,
    'Trinidad And Tobago': null,
    Tunisia: null,
    Turkey: null,
    Turkmenistan: null,
    Uganda: null,
    Ukraine: null,
    'United Arab Emirates, The': null,
    'United Kingdom, The': null,
    Uruguay: null,
    Uzbekistan: null,
    Vanuatu: null,
    Venezuela: null,
    Vietnam: null,
    Yemen: null,
    Zambia: null,
    Zimbabwe: null,
  });

  return [countries, setCountries];
};

export default useCountries;
