import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ben&apos;s Atlas</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/atlas.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.landing}>
          <h1 className={styles.heading}>
            <span
              className={`${styles.welcome} text-[#80b6ec] font-serif`}
            >
              Welcome to
            </span>
            <br />
            <span
              className={`${styles.title} text-[#80b6ec] font-serif font-semi-bold`}
            >
              Ben&apos;s Atlas
            </span>
          </h1>
          <div className={`flex ${styles.buttons}`}>
            <div className="w-24 my-2 ml-2 mr-4 p-2 bg-indigo-500 rounded-xl text-white text-center">
              <Link href="/signin">Sign In</Link>
            </div>
            <div className="w-24 m-2 p-2 bg-indigo-500 rounded-xl text-white text-center">
              <Link href="/signup">Sign Up</Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
